package consistent

// code generated by "go generate" - DO NOT EDIT

var rangeExprStyles = map[uint16]string{
	340: "center",
	354: "right",
	360: "left",
	402: "right",
	408: "left",
	417: "outside",
	593: "outside",
	610: "right",
	616: "left",
	658: "right",
	664: "left",
	676: "center",
}
